version: '3'
services:
    redis:
        image: "redis:alpine"
        expose:
            - 6379
        volumes: 
            - redis-data:/data
    app:
        build:
            context: ./build
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www
        ports:
            - "10.8.0.1:7000:80"
        env_file:
            - ".env"
        links:
            - redis
volumes:
    redis-data: {}
