version: '3'
services:
    redis:
        image: "redis:alpine"
        expose:
            - 6379
        volumes: 
            - redis-data:/data
    soxokienthiet:
        build:
            context: ./build
            dockerfile: Dockerfile
            args: 
                - USER_ID=1000
                - GROUP_ID=1000
        volumes:
            - ./:/var/www
        ports:
            - "8801:80"
        env_file:
            - ".env"
        links:
            - redis
    redis-manager:
        image: "erikdubbelboer/phpredisadmin"
        ports:
            - "8802:80"   
        environment:
            - REDIS_1_HOST=redis
            - REDIS_1_NAME=redis
            - REDIS_1_PORT=6379

volumes:
    redis-data: {}
